/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GameCard: typeof import('./src/components/GameCard.vue')['default']
    HangmanGame: typeof import('./src/components/hangman/HangmanGame.vue')['default']
    HangmanHelpDialog: typeof import('./src/components/hangman/HangmanHelpDialog.vue')['default']
    HangmanStartDialog: typeof import('./src/components/hangman/HangmanStartDialog.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
