name: afterwork-coding
channels:
  - conda-forge
dependencies:
  - python=3.12.8
  - pip=25.0.0
  - pip:
      - black==25.1.0
      - httpx==0.28.1
      - factory-boy==3.3.1
      - flake8==7.1.1
      - passlib==1.7.4
      - PyJWT==2.10.1
      - isort==6.0.0
      - pytest==8.3.5
      - pytest-asyncio==0.25.3
      - pydantic-settings==2.7.1
      - fastapi[standard]==0.115.6
      - sqlmodel==0.0.22
      - pyright==1.1.399
